[control]
url = "mqtt://localhost:1883"
user = "mqtt"
pass = "pass"
topic = "control"

[target]
url = "mqtt://localhost:1883"
user = "mqtt"
pass = "pass"
devices = 10
data_points = 10
wait_time_secs = 10
seed = 1
