[package]
name = "rumsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.13", features = ["toml"] }
lazy_static = "1.4"
rumqttc = { version = "0.22", features = ["url"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.30", features = ["rt", "rt-multi-thread", "macros"] }
env_logger = "0.10"
log = "0.4"
rand = "0.8"
